### ISSUE TITLE
[Feature Request] Add Windows and Mac support to it pls 

### ISSUE THREAD

**Issue by CoderLogy** [MCPI-Revival/jMCPIL#1]
Make windows version for this jmcpil pls guys it would really help u can also put this game on steam etc supper good pls doit man and solve this issue

**Comment by NoozAbooz** [comment]
> Make windows version for this jmcpil
Minecraft Pi is meant for Linux systems as it uses docker. Feel free to use something like wsl or a linux vm to run it.

**Comment by NoozAbooz** [comment]
> u can also put this game on steam etc supper good pls doit man

We're a modding project, we don't have the funds to put this game on steam and it would be useless if we did, since.it might garner mojang's attention and take the listing down.

**Comment by TheBrokenRail** [comment]
MCPI is a Linux game. Even if jMCPIL ran on Windows, it would be redundant since the game itself does not run on Windows.
