### ISSUE TITLE
Broken rail can u tell how do u write this much code and how do u have in mind without seeking youtube tutorial pls help man

### ISSUE THREAD

**Issue by CoderLogy** [MCPI-Revival/jMCPIL#2]
same as title

**Comment by CoderLogy** [comment]
How u coded this which tutorial like how and how do u even write thoose some big code in python too pls help are u pro devloper too

**Comment by NoozAbooz** [comment]
> How u coded this which tutorial like how and how do u even write thoose some big code in python too pls help are u pro devloper too

We all have general experience in coding stuff, if you know the basics, try a advanced or intermediate tutorial and practice by contributing to other apps, or make your own. We just write big pieces of python code as we go along, slowly testing each element or changing ones to fix bugs.

**Comment by TheBrokenRail** [comment]
This is not an issue with jMCPIL. Ask questions like this on the Discord.
