### ISSUE TITLE
[Feature Request] Be able to compile to JAR

### ISSUE THREAD

**Issue by ghost** [MCPI-Revival/jMCPIL#3]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.  
I want a platform independent version of mcpi.

**Describe the solution you'd like**
Allow compilation to JAR and the game to EXE. GCC maybe?

**Describe alternatives you've considered**
Manually compiling.

**Additional context**
Gamer moment

**Comment by TheBrokenRail** [comment]
Just run ``./gradlew build``? I don't really see any purpose though since MCPI itself is Linux only.

**Comment by ghost** [comment]
Oh.
